### ISSUE TITLE
Failed to enable plugin (blender v3.1)

### ISSUE THREAD

**Issue by Dushess** [REDxEYE/blender_xna#2]
Which requirements do I need to follow? Or it is not ready yet, v.0.0.2 means something early.
Currently I have this:
![XNA plugin error](https://github.com/REDxEYE/blender_xna/assets/15954961/fe80edc7-0425-415c-acb3-47956d19d1ab)

**Comment by REDxEYE** [comment]
You need to also copy [py_xna_lib](https://github.com/REDxEYE/py_xna_lib/tree/5b2854463a4423a6a6b010390d85ebc3afea6b27) and place it into addon folder. Make sure folder is named py_xna_lib and nothing else

**Comment by Dushess** [comment]
Do I need to perform something else, It had no effect.

**Comment by Dushess** [comment]
Done, specifically in System drive, Roaming area,.. set up complete, 07

**Comment by Dushess** [comment]
well, result is no XNA line in Import page XD

**Comment by REDxEYE** [comment]
Are you sure it's properly enabled?

**Comment by Dushess** [comment]
yes, now finally did it

**Comment by REDxEYE** [comment]
So it works?

**Comment by Dushess** [comment]
Lol, not yet, may be model specific, I tried only one right now.
![image](https://github.com/REDxEYE/blender_xna/assets/15954961/64ba1c89-57aa-43cf-b067-a5702429d997)

Yes, probably that's because how those models were packed up and now this plugin can't read 'em. Some other works fine.
Found that reason is different mesh structure, not supported here, specific for XPS 11.8.9
